1 install ojdbc8.jar

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -1,47 +1,50 @@
 name: GitHub Actions Demo
-#on:
-#  push:
-#    branches: [ "main" ]
-#  pull_request:
-#    branches: [ "main" ]
-jobs:
-  job1:
-    name: this is job1
-    runs-on: ubuntu-latest
-    steps:
-      - name: Pull Docker image
-        run: |
-          docker pull registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
+on:
+  push:
+    branches: [ "main" ]
 
-      - name: run oracle container
-        run: |
-          docker run -d --name oracle19c -p 1521:1521 \
-          -e ORACLE_SID=ORCL -e ORACLE_PDB=ORCLPDB -e ORACLE_PWD=Oracle123 \
-          -e ORACLE_EDITION=standard -e ORACLE_CHARACTERSET=AL32UTF8 \
-          registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
-      - name: Verify DM Database is running
-        shell: bash
-        run: |
-          docker ps 
-          sleep 10
-          while true
-          do
-            echo 1
-            log_output=$(docker logs oracle19c 2>&1 | grep -i "XDB initialized." || true)
-            echo log_output=$log_output
-            echo 2
-            if [ -z "$log_output" ]; then
-              echo "'complete' not found in the logs, retrying in 10 seconds..."
-              sleep 10
-            else
-              echo "'XDB initialized.' found in the logs, continuing."
-              break
-            fi
-          done
-          echo connect oracle
-          docker exec oracle19c sqlplus system/Oracle123@127.0.0.1:1521/ORCLPDB
-          sleep 30
-          telnet 127.0.0.1 1521
+jobs:
+  use-oracle-service:
+    uses: ./.github/workflows/workflow-windows-docker.yml
+    with:
+      ports: 1521 1522 1523
+#  job1:
+#    name: this is job1
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Pull Docker image
+#        run: |
+#          docker pull registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
+#
+#      - name: run oracle container
+#        run: |
+#          docker run -d --name oracle19c -p 1521:1521 \
+#          -e ORACLE_SID=ORCL -e ORACLE_PDB=ORCLPDB -e ORACLE_PWD=Oracle123 \
+#          -e ORACLE_EDITION=standard -e ORACLE_CHARACTERSET=AL32UTF8 \
+#          registry.cn-hangzhou.aliyuncs.com/zhuyijun/oracle:19c
+#      - name: Verify DM Database is running
+#        shell: bash
+#        run: |
+#          docker ps
+#          sleep 10
+#          while true
+#          do
+#            echo 1
+#            log_output=$(docker logs oracle19c 2>&1 | grep -i "XDB initialized." || true)
+#            echo log_output=$log_output
+#            echo 2
+#            if [ -z "$log_output" ]; then
+#              echo "'complete' not found in the logs, retrying in 10 seconds..."
+#              sleep 10
+#            else
+#              echo "'XDB initialized.' found in the logs, continuing."
+#              break
+#            fi
+#          done
+#          echo connect oracle
+#          docker exec oracle19c sqlplus system/Oracle123@127.0.0.1:1521/ORCLPDB
+#          sleep 30
+#          telnet 127.0.0.1 1521
 
 #  job2:
 #    name: this is job2
